version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    depends_on:
      - database
  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
  ai:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./ai:/app
    depends_on:
      - backend
  scheduling:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./scheduling:/app
    depends_on:
      - backend
  file_system:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./file_system:/app
    depends_on:
      - backend
  aws:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./AWS/EC2:/app
    depends_on:
      - backend
  heroku:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Heroku:/app
    depends_on:
      - backend

This is the generated code for the docker-compose.yml file.